// nextjs/components/ScrollTop.jsx
import {useEffect, useState} from "react";

export default function ScrollTop() {
    const [show, setShow] = useState(false);

    useEffect(() => {
        window.onscroll = () => {
            setShow(window.scrollY > 0);
        }
    }, []);

    const handleAnchorClick = (event) => {
        event.preventDefault();
        window.scrollTo({
			top: 0,
			behavior: 'smooth'
		})
    }

    return (
        <span
            className={`scroll-top ${show ? 'display' : ''}`}
            onClick={handleAnchorClick}
            >
            <svg
                xmlns="http://www.w3.org/2000/svg"
                width="22"
                height="22"
                viewBox="0 0 32 32"
                ><path className="scroll-to-top-btn-icon" d="M30,22.656l-14-13-14,13" /></svg
            >
        </span>
    )
}

// angular/src/app/components/shared/scroll-top/scroll-top.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-scroll-top',
  templateUrl: './scroll-top.component.html',
  styleUrls: ['./scroll-top.component.scss'],
})
export class ScrollTopComponent implements OnInit {
  show: boolean = false;
  ngOnInit(): void {
    window.onscroll = () => {
      this.show = window.scrollY > 0;
    };
  }

  handleAnchorClick(event: any) {
    event.preventDefault();
    window.scrollTo({
      top: 0,
      behavior: 'smooth',
    });
  }
}

<span class="scroll-top" [class.display]="show" (click)="handleAnchorClick($event)">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="22"
      height="22"
      viewBox="0 0 32 32"
      ><path class="scroll-to-top-btn-icon" d="M30,22.656l-14-13-14,13" />
      </svg>
  </span>
