// nextjs/components/Navbar.jsx
import { useState } from "react";

export default function Layout({ props }) {
  const [display, setDisplay] = useState(false);

  const toggle = () => {
    setDisplay(!display);
  };

  return (
    <>
      <div className="bloc nav l-bloc" id="bloc-0">
        <div className="container bloc-sm">
          <div className="row">
            <div className="col">
              <nav className="navbar row navbar-light">
                <a className="navbar-brand" href="/">
                  <img
                    src="https://www.satellit.be/img/satellit-logo-rvb_1_orig.png"
                    alt="logo-satellit"
                  />
                </a>
                <button
                  id="nav-toggle"
                  type="button"
                  className="ml-auto ui-navbar-toggler navbar-toggler border-0 p-0 menu-icon-rounded-bars toggle-btn"
                  onClick={toggle}
                >
                  <span className="navbar-toggler-icon"></span>
                </button>
                {/* if */}
                {display && <div className="navbar-collapse fullscreen-nav">
                  <button
                    onClick={toggle}
                    type="button"
                    className="close"
                    aria-label="Close"
                  >
                    <span aria-hidden="true">&times;</span>
                  </button>
                  <ul className="site-navigation nav navbar-nav">
                    <li className="nav-item">
                      <a href="/" className="nav-link a-btn">
                        Home
                      </a>
                    </li>
                    <li className="nav-item nav-link">
                      <a href="/about-us" className="nav-link a-btn">
                        About us
                      </a>
                    </li>
                    <li className="nav-item nav-link">
                      <a href="/jobs" className="nav-link a-btn">
                        Jobs
                      </a>
                    </li>
                    <li className="nav-item nav-link">
                      <a href="/community" className="nav-link a-btn">
                        Community
                      </a>
                    </li>
                    <li className="nav-item">
                      <a href="/training-center" className="nav-link a-btn">
                        Training center
                      </a>
                    </li>
                    <li className="nav-item nav-link">
                      <a href="/contact" className="nav-link a-btn">
                        Contact us
                      </a>
                    </li>
                    <li className="nav-item nav-link">
                      <a href="/portal" className="nav-link a-btn">
                        Login
                      </a>
                    </li>
                  </ul>
                </div>}
              </nav>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// angular/src/app/components/shared/navbar/navbar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
})
export class NavbarComponent {
  display: boolean = false;
  toggle(): void {
    this.display =!this.display;
  }
}

<div class="bloc nav l-bloc" id="bloc-0">
  <div class="container bloc-sm">
    <div class="row">
      <div class="col">
        <nav class="navbar row navbar-light">
          <a class="navbar-brand" href="/">
            <img
              src="https://www.satellit.be/img/satellit-logo-rvb_1_orig.png"
              alt="logo-satellit"
            />
          </a>
          <button
            id="nav-toggle"
            type="button"
            class="ml-auto ui-navbar-toggler navbar-toggler border-0 p-0 menu-icon-rounded-bars toggle-btn"
            (click)="toggle()"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <ng-container *ngIf="display">
            <div class="navbar-collapse fullscreen-nav">
              <button
                (click)="toggle()"
                type="button"
                class="close"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
              <ul class="site-navigation nav navbar-nav">
                <li class="nav-item">
                  <a href="/" class="nav-link a-btn">Home</a>
                </li>
                <li class="nav-item nav-link">
                  <a href="/about-us" class="nav-link a-btn">About us</a>
                </li>
                <li class="nav-item nav-link">
                  <a href="/jobs" class="nav-link a-btn">Jobs</a>
                </li>
                <li class="nav-item nav-link">
                  <a href="/community" class="nav-link a-btn">Community</a>
                </li>
                <li class="nav-item">
                  <a href="/training-center" class="nav-link a-btn"
                    >Training center</a
                  >
                </li>
                <li class="nav-item nav-link">
                  <a href="/contact" class="nav-link a-btn">Contact us</a>
                </li>
              </ul>
            </div>
          </ng-container>
        </nav>
      </div>
    </div>
  </div>
</div>
