// sveltekit/src/components/LetsTalk.svelte
<div class="container bloc-lg">
    <div class="row">
      <div class="col">
        <h2 class="h2-style text-lg-center mg-md">
          <div class="text-center">
            <a href="contact.html">Let’s talk</a>
          </div>
        </h2>
        <div class="green-line">
          <svg
            width="200"
            height="44"
            viewBox="0 0 212 14"
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            fill="#2DCE94"
            stroke="rgba(0,0,0,0.0)"
            stroke-linecap="round"
            stroke-width="0"
          >
            <defs>
              <linearGradient
                x1="91.2099154%"
                y1="52.4730393%"
                x2="16.4955172%"
                y2="49.1639271%"
                id="linearGradient-3k851zev7c-1"
              >
                <stop stop-color="#D9CF7D" offset="0%"></stop>
                <stop stop-color="#CACD7D" offset="6.86964459%"></stop>
                <stop stop-color="#00BA82" offset="100%"></stop>
              </linearGradient>
            </defs>
            <g
              id="Page-1"
              stroke="none"
              stroke-width="1"
              fill="none"
              fill-rule="evenodd"
            >
              <g
                transform="translate(-668.000000, -744.000000)"
                fill="url(#linearGradient-3k851zev7c-1)"
              >
                <path
                  d="M841.549535,752.054288 C741.951859,748.433027 693.07392,756.50086 670.952735,757.995852 C668.248925,758.178431 667.989667,752.280659 667.999717,750.90559 C668.066545,742.22669 878.582564,742.367498 879.85432,747.7876 C880.337668,749.848519 879.651493,752.843891 877.296087,752.612804 C869.324511,751.830612 855.555202,752.054288 841.549535,752.054288 L982,806.957031"
                  id="Fill-1"></path>
              </g>
            </g>
          </svg>
        </div>
        <p class="p-81-style text-lg-center mx-auto d-block big-p">
          Feel free to contact us for any question. Our team is always glad to
          help you on your projects.
        </p><a href="/contact"
          ><img
            src="https://www.satellit.be/img/Group-46.png"
            class="img-fluid mx-auto d-block ls-is-cached lazyloaded"
          />
        </a>
      </div>
    </div>
  </div>

  <style>
    .p-81-style {
    width: 44.38%;
  }
  .big-p {
    font-size: 21px;
    line-height: 30px;
    width: 80.23%;
    margin-top: 25px;
  }
  a {
    color: #1a191d !important;
  }
  a:hover {
    text-decoration: none;
    cursor: pointer;
  }
  .bloc-lg {
    padding: 100px 20px;
  }
  </style>

// solid/src/components/LetsTalk.jsx
export default function LetsTalk() {
  return (
    <div className="container bloc-lg">
      <div className="row">
        <div className="col">
          <h2 className="h2-style text-lg-center mg-md">
            <div className="text-center">
              <a className="letsTalk" href="contact.html">Let’s talk</a>
            </div>
          </h2>
          <div className="green-line">
            <svg
              width="200"
              height="44"
              viewBox="0 0 212 14"
              version="1.1"
              fill="#2DCE94"
              stroke="rgba(0,0,0,0.0)"
              strokeLinecap="round"
              strokeWidth="0"
            >
              <defs>
                <linearGradient
                  x1="91.2099154%"
                  y1="52.4730393%"
                  x2="16.4955172%"
                  y2="49.1639271%"
                  id="linearGradient-3k851zev7c-1"
                >
                  <stop stopColor="#D9CF7D" offset="0%"></stop>
                  <stop stopColor="#CACD7D" offset="6.86964459%"></stop>
                  <stop stopColor="#00BA82" offset="100%"></stop>
                </linearGradient>
              </defs>
              <g
                id="Page-1"
                stroke="none"
                strokeWidth="1"
                fill="none"
                fillRule="evenodd"
              >
                <g
                  transform="translate(-668.000000, -744.000000)"
                  fill="url(#linearGradient-3k851zev7c-1)"
                >
                  <path
                    d="M841.549535,752.054288 C741.951859,748.433027 693.07392,756.50086 670.952735,757.995852 C668.248925,758.178431 667.989667,752.280659 667.999717,750.90559 C668.066545,742.22669 878.582564,742.367498 879.85432,747.7876 C880.337668,749.848519 879.651493,752.843891 877.296087,752.612804 C869.324511,751.830612 855.555202,752.054288 841.549535,752.054288 L982,806.957031"
                    id="Fill-1"
                  ></path>
                </g>
              </g>
            </svg>
          </div>
          <p className="p-81-style text-lg-center mx-auto d-block big-p">
            Feel free to contact us for any question. Our team is always glad to
            help you on your projects.
          </p>
          <a className="letsTalk" href="/contact">
            <img
              src="https://www.satellit.be/img/Group-46.png"
              className="img-fluid mx-auto d-block ls-is-cached lazyloaded"
            />
          </a>
        </div>
      </div>
    </div>
  );
}
