// nextjs/components/SpecialCard.jsx
export default function SpecialCard(props) {
  return (
    <div className={props.cssClass}>
      <img
        src={props.link}
        className="img-fluid mx-auto d-block ls-is-cached"
        alt="placeholder image"
      />
      <h5 className="mg-md text-lg-center tc-dark-jungle-green h5-style">
        {props.title}
      </h5>
      <p className="text-lg-center big-p p-style mx-auto d-block">{props.description}</p>
    </div>
  );
}

// angular/src/app/components/home/special-card/special-card.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-special-card',
  templateUrl: './special-card.component.html',
  styleUrls: ['./special-card.component.scss']
})
export class SpecialCardComponent {
  @Input() link!: string;
  @Input() title!: string;
  @Input() description!: string;
  @Input() cssClass!: string;
}

<div [class]="cssClass">
  <img
    [src]="link"
    class="img-fluid mx-auto d-block ls-is-cached"
    alt="placeholder image"
  />
  <h5 class="mg-md text-lg-center tc-dark-jungle-green h5-style">
    {{ title }}
  </h5>
  <p class="text-lg-center big-p p-style mx-auto d-block">
    {{ description }}
  </p>
</div>
